# configs/config.yaml

# 词汇表大小将由脚本动态确定，我们在这里定义特殊标记的ID
special_tokens:
  unk_idx: 0
  pad_idx: 1
  sos_idx: 2
  eos_idx: 3

model:
  # vocab_size_src 和 vocab_size_tgt 将在 run.py 中动态添加
  max_seq_len: 256
  embed_dim: 256
  hidden_dim: 512
  num_encoder_layers: 4
  num_decoder_layers: 4
  encoder_kernel_size: 3
  decoder_kernel_size: 3
  dropout: 0.25 # 稍微增加dropout以防止过拟合

training:
  learning_rate: 0.0005 # 降低一点学习率可能更稳定
  batch_size: 128 # 增加批次大小以充分利用GPU
  num_epochs: 10
  device: "auto"
  clip_grad: 1.0 # 梯度裁剪的阈值